# Generated by Django 3.2.1 on 2021-06-09 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_cnt',
            fields=[
                ('class_cnt_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('problem_cnt', models.BigIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='problem',
            fields=[
                ('problem_id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('answer', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('blank_num', models.IntegerField()),
                ('info', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='problems/')),
                ('text', models.TextField(blank=True, null=True)),
                ('blank_text', models.TextField(blank=True, null=True)),
                ('translation_text', models.TextField(blank=True, null=True)),
                ('problem_image', models.ImageField(blank=True, null=True, upload_to='results/')),
                ('keyword_duplicate', models.BooleanField(default=True)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.monitor')),
            ],
        ),
    ]
